name: Deploy to OVH (SFTP)

on:
  push:
    branches: [ "main" ]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.cluster100.hosting.ovh.net
          username: fastfoq
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          protocol: sftp
          local-dir: ./
          server-dir: /home/fastfoq/soulmade/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules*
            **/vendor*
