name: Deploy ALL files to SFTP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload all files via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ftp.cluster100.hosting.ovh.net
          username: fastfoq
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "."
          target: "/home/fastfoq/soulmade/"
          strip_components: 0
